### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by AhmedAfifi00** [eslam3kl/GG-Dorking#5]
python3 gg_dorking.py domain.com 
Traceback (most recent call last):
  File "gg_dorking.py", line 4, in <module>
    import jinja2
  File "/home/kali/.local/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/kali/.local/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/kali/.local/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/kali/.local/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/kali/.local/lib/python3.8/site-packages/markupsafe/__init__.py)

**Comment by R3dHash** [comment]
Removing the jinja2 specific version in requirements.txt worked for me. One changed just run pip3 install jinja2 -U.

**Comment by doxyf** [comment]
You need to install older (supported) version:
`pip uninstall markupsafe` then `pip install markupsafe==2.0.1`
